Agent_settings:
  Output_csv: 'output/csv/entrenamiento/diff_waiting_time'
  Output_model: 'output/models/entrenamiento/diff_waiting_time'
  Environment:
    Gui: False
    Num_seconds: 10000
    Min_green: 4
    Max_green: 60
    Yellow_time: 3
    Delta_time: 4
  Instances:
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 5
      Alpha: 0.00005
      Gamma: 0.5
      Epsilon: 0.01
      FourierOrder: 7
      Lambda: 0.999
    Fixed_run:
      Agent_type: 'FIXED'
      Runs: 1
      

